version: '3'
services:
  client:
    build:
      dockerfile: dockerFile.dev
      context: ./
    container_name: client
    ports:
      - "3000:3000"
    env_file:
      - ./.env.dev
    volumes:
      - ./:/client
      - /node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
